trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('add_information/', views.create, name='add_information'),
    path('account_information/', views.view_account_info, name='account_information'),
    path('change_pickup/', views.change_pickup, name='change_pickup'),
    path('suspend_pickup/', views.suspend_pickup, name='suspend_pickup'),
    path('view_bill/', views.view_bill, name='view_bill'),
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/customers/models.py
from django.db import models
from django.contrib.auth.models import Group


# Create your models here.

# TODO: Finish customer model by adding necessary properties to fulfill user stories


class Customer(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    pickup_address = models.CharField(max_length=50, default='address')
    pickup_city = models.CharField(max_length=50, default='city')
    pickup_state = models.CharField(max_length=2, default='state')
    pickup_zip = models.CharField(max_length=50, default=48217)
    pickup_day = models.CharField(max_length=20, default='Monday')
    pickup_suspended = models.BooleanField(default=False)
    amount_due = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    pickup_status = True

    def __str__(self):
        return self.name

trash_collector/customers/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Customer


# Create your views here.

# TODO: Create a function for each path created in customers/urls.py. Each will need a template as well.


def index(request):
    # The following line will get the logged-in in user (if there is one) within any view function
    user = request.user
    # It will be necessary while creating a customer/employee to assign the logged-in user as the user foreign key
    # This will allow you to later query the database using the logged-in user,
    # thereby finding the customer/employee profile that matches with the logged-in user.
    print(user)
    return render(request, 'customers/index.html')


def create(request):
    if request.method == 'POST':
        user = request.user
        name = request.POST.get('name')
        pickup_day = request.POST.get('pickup_day')
        pickup_address = request.POST.get('pickup_address')
        pickup_city = request.POST.get('pickup_city')
        pickup_state = request.POST.get('pickup_state')
        pickup_zip = request.POST.get('pickup_zip')
        new_customer = Customer(user=user, name=name, pickup_day=pickup_day, pickup_address=pickup_address,
                                pickup_city=pickup_city, pickup_state=pickup_state, pickup_zip=pickup_zip)
        new_customer.save()
        return HttpResponseRedirect(reverse('customers:account_information'))
    else:
        return render(request, 'customers/add_information.html')


def view_account_info(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    context = {
        "customer": customer
    }
    return render(request, 'customers/account_information.html', context)


def view_bill(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    total_amount_due = customer.amount_due
    context = {
        "total_amount_due": total_amount_due
    }
    return render(request, 'customers/view_bill.html', context)


def change_pickup(request):
    if request.method == 'POST':
        user = request.user
        old_day = Customer.pickup_day.get(user=user)
    return render(request, 'customers/change_pickup.html')
    pass


def suspend_pickup(request):
    context = {

    }
    return render(request, 'customers/suspend_pickup.html', context)

# if request.method == 'POST':
# user = request.user
# name = request.POST.get('name')
# pickup_day = request.POST.get('pickup_day')
# pickup_address = request.POST.get('pickup_address')
# pickup_city = request.POST.get('pickup_city')
# pickup_state = request.POST.get('pickup_state')
# pickup_zip = request.POST.get('pickup_zip')
# user = Customer(user=user, name=name, pickup_day=pickup_day, pickup_address=pickup_address, pickup_city=pickup_city,
#                 pickup_state=pickup_state, pickup_zip=pickup_zip)
# user.save()

trash_collector/customers/templates/customers/Home.html
{% extends 'base.html' %}

{% block header%}

trash_collector/customers/templates/customers/account_information.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block content %}
    <h1> Account Information <h1>
    <h3> Hello {{customer.name}}!! Here is where you can View your account information!</h3>
    <ul>
        <li>{{customer.name}}</li>
        <li>Address: {{customer.pickup_address}}</li>
        <li>Residence: {{customer.pickup_city}}</li>
        <li>State: {{customer.pickup_state}}</li>
        <li>Zip: {{customer.pickup_zip}}</li>
        <li>Pickup Day: {{customer.pickup_day}}</li>
        <li>Account Balance: {{customer.account_balance}}</li>
    </ul>

{% endblock %}

trash_collector/customers/templates/customers/add_information.html
{% extends 'base.html' %}

{% block title %}Add Information{% endblock %}

{% block content %}
    <h1>Enter Your Information</h1>
    <div>
        <form action="{% url 'customers:add_information' %}" method="post"> {% csrf_token %}
            <div>
                <div>
                    <label>Name</label>
                    <input class="form-control" type="text" name="name" id="name">
                </div>
                <div class="form-group">
                    <label>Address</label>
                    <input class="form-control" type="text" name="pickup_address" id="address">
                </div>
                <div class="form-group">
                    <label>City</label>
                    <input class="form-control" type="text" name="pickup_city" id="city">
                </div>
                <div class="form-group">
                    <label>State</label>
                    <input class="form-control" type="text" name="pickup_state" id="state">
                </div>
                <div class="form-group">
                    <label>Zip Code</label>
                    <input class="form-control" type="text" name="pickup_zip" id="zip">
                </div>
                <div class="form-group">
                    <label>Pickup Day</label>
                    <input class="form-control" type="text" name="pickup_day" id="pickup day">
                </div>
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </form>
    </div>

{% endblock %}

trash_collector/customers/templates/customers/change_pickup.html
{% extends 'base.html' %}

trash_collector/customers/templates/customers/index.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Customer Home {% endblock %}

{% block header %} Customer Home {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <p>Welcome {{user.username}}! Thank you for choosing The Green Team! We greatly appreciate your business!
      Registered customers can view their information in the navigation bar above!
      If you are a new customer please <a href="{% url 'customers:add_information' %}">Click Here!</a> to register.</p>
  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/suspend_pickup.html
{% extends 'base.html' %}

trash_collector/customers/templates/customers/view_bill.html
{% extends 'base.html' %}